                                         # ----------- Exceptions

import builtins
from os import error, name


# builtins errors
'''Exceptions mean error, when occure we put our code in try block and strike with except blocks (one or more)
except blocks caught the exceptioms and make exception handling. when no exception found Then 
else block execute but the finally block compulsory executes either Exceptions or not'''

# basic concept
'''a = 10
b = 3           # if b = 0 then divided by zero will occures, else will not execute
try:
    d = a//b
    print(d)
   

except:
        print( 'some error is occuring')

else:
    print('in the else block,(no exception found)')

finally:
    print('finally block compulsory prints\n')

print('the rest code here')
print('\n')'''
        # -------------types of errors

# IndexError    (index of sequence is out of range)
'''list1 = ['corona virus', 'flu','Smallpox']
try:
    print('the last virus is',list1[5]) # list1[5] not exist (out of range)
except IndexError as obj:
    print(obj)
else:
    print('no exception found')
finally:
    print('in the finally block')
print('\n')'''
# ModuleNotFoundError 
'''try:
    from module import n_add        # module1 is correct so, no module found
    print(n_add(6))
except (ModuleNotFoundError, SyntaxError ) as obj:
    print(obj, 'error here')
else:
    print('no exception found')
print('\n')'''
# KeyError
'''dict1 = dict(name = 'farooq', caste = 'butt', roll_num = 660)
try:
    print(dict1['roll_number'])     # roll_num is correct now key error will occure
except (KeyError,SyntaxError, ValueError, TypeError) as obj:
    print (obj,'key not found')
else:
    print('no exception found')'''
# NameError
'''a = 'butt sb'
try:      
    print(b)        # 'a' is defined not 'b'
except (NameError, SyntaxError,LookupError,IndentationError) as obj:
    print(obj, 'exception')     # not defined error
else:
    print('no exception found')'''
# ZeroDivisionError
'''a = 10
b = 5
c = 0       # if c != 0 then no exception found

x = a//b
print(x)

try:
    y = a//c
    print(y)

except(ZeroDivisionError,SyntaxError,IndentationError) as obj:
    print(obj)              # p//q 'q' should not be zero. zero division error

else:
    print("no error found")'''
# AssertionError
'''num = int(input('plz enter the even number : '))
try:
    assert num%2 == 0       # assert mean condition will always true
    # print('the number is even')
except AssertionError:
    print(AssertionError,'plz enter even number. ')
else:
    print('good your number is even')
finally:
    print('here is rest of the code. ')'''
# SyntaxError       not working properly
'''a =int(40)
b = 30

try:
    c = a + b
    print(c).
except (SyntaxError, IndentationError):
    print(SyntaxError')
else:
    print('no error found')
finally:
    ('rest of the code')'''
'''# IOError 
try:
   new_file = open("butt_file", "r")    # if we put 'w' instead of 'r' then no error found 
   new_file.write("this file is generated by open() method")
except (IOError,OSError) as obj:
   print (obj,'file')
else:
   print ("no error found in creating the writablefile")
   new_file.close()'''